
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar  3 2023 09:50:34 +07 (Mar  3 2023 02:50:34 UTC)

// Verification Directory fv/bound_flash 

module bound_flash(clk, reset, flick, state, out);
  input clk, reset, flick;
  output [3:0] state;
  output [15:0] out;
  wire clk, reset, flick;
  wire [3:0] state;
  wire [15:0] out;
  wire [4:0] count;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_8, n_9;
  wire n_10, n_11, n_13, n_14, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_46;
  wire n_47, n_48, n_50, n_51, n_53, n_55, n_57, n_58;
  wire n_61, n_62, n_63, n_67, n_69, n_71, n_73, n_75;
  wire n_76, n_77, n_79, n_81, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_128, n_129;
  assign state[3] = 1'b0;
  DFFHQX8 \count_reg[1] (.CK (clk), .D (n_124), .Q (count[1]));
  DFFRHQX4 \state_reg[0] (.RN (n_120), .CK (clk), .D (n_123), .Q
       (state[0]));
  OAI211X1 g3003__2398(.A0 (n_105), .A1 (n_119), .B0 (n_96), .C0
       (n_115), .Y (n_124));
  DFFHQX8 \count_reg[0] (.CK (clk), .D (n_121), .Q (count[0]));
  DFFHQX8 \count_reg[2] (.CK (clk), .D (n_122), .Q (count[2]));
  DFFHQX8 \count_reg[3] (.CK (clk), .D (n_117), .Q (count[3]));
  DFFHQX8 \count_reg[4] (.CK (clk), .D (n_118), .Q (count[4]));
  NAND2X1 g3002__5107(.A (n_110), .B (n_116), .Y (n_123));
  OAI211X1 g3007__6260(.A0 (n_58), .A1 (n_87), .B0 (n_109), .C0
       (n_103), .Y (n_122));
  AO22X1 g3008__4319(.A0 (n_120), .A1 (n_108), .B0 (count[0]), .B1
       (n_119), .Y (n_121));
  OAI221X1 g3012__8428(.A0 (n_79), .A1 (n_98), .B0 (n_128), .B1
       (n_119), .C0 (n_86), .Y (n_118));
  OAI2BB1X1 g3013__5526(.A0N (count[3]), .A1N (n_99), .B0 (n_112), .Y
       (n_117));
  AOI21X1 g3006__6783(.A0 (state[0]), .A1 (n_85), .B0 (n_107), .Y
       (n_116));
  AOI31X2 g3015__3680(.A0 (n_77), .A1 (n_89), .A2 (n_111), .B0 (n_19),
       .Y (n_115));
  OAI2BB1X1 g3020__1617(.A0N (n_25), .A1N (n_128), .B0 (n_102), .Y
       (n_114));
  AOI31X2 g3021__2802(.A0 (n_53), .A1 (n_93), .A2 (n_111), .B0 (n_104),
       .Y (n_112));
  AOI2BB1X1 g3009__1705(.A0N (state[1]), .A1N (n_91), .B0 (n_62), .Y
       (n_110));
  NAND2X1 g3017__5122(.A (n_94), .B (n_111), .Y (n_109));
  OAI22X1 g3019__8246(.A0 (count[0]), .A1 (n_88), .B0 (state[2]), .B1
       (n_28), .Y (n_108));
  NAND2BX1 g3014__7098(.AN (n_50), .B (n_95), .Y (n_107));
  OAI32X1 g3016__6131(.A0 (n_69), .A1 (n_48), .A2 (n_105), .B0 (n_101),
       .B1 (n_100), .Y (n_106));
  NOR3BX1 g3056__1881(.AN (n_90), .B (n_73), .C (n_119), .Y (n_104));
  OR4X1 g3068__5115(.A (count[2]), .B (n_84), .C (n_38), .D (n_119), .Y
       (n_103));
  NAND2BX1 g3024__7482(.AN (n_101), .B (n_100), .Y (n_102));
  OAI21X1 g3027__4733(.A0 (state[0]), .A1 (n_92), .B0 (n_97), .Y
       (n_99));
  AND2X1 g3035__6161(.A (n_40), .B (n_97), .Y (n_98));
  OAI21X1 g3042__9315(.A0 (n_27), .A1 (n_119), .B0 (count[1]), .Y
       (n_96));
  AOI221X1 g3018__9945(.A0 (n_23), .A1 (n_39), .B0 (n_6), .B1 (n_30),
       .C0 (n_33), .Y (n_95));
  OA21X1 g3031__2883(.A0 (n_17), .A1 (n_93), .B0 (n_92), .Y (n_94));
  AOI221X1 g3032__2346(.A0 (count[1]), .A1 (n_90), .B0 (flick), .B1
       (n_129), .C0 (n_81), .Y (n_91));
  INVX1 g3037(.A (n_88), .Y (n_89));
  NOR2X1 g3041__1666(.A (n_31), .B (n_119), .Y (n_87));
  NAND2X1 g3034__7410(.A (n_47), .B (n_111), .Y (n_86));
  OAI22X1 g3036__6417(.A0 (count[1]), .A1 (n_41), .B0 (n_84), .B1
       (state[2]), .Y (n_85));
  OAI21X1 g3033__5477(.A0 (n_84), .A1 (n_76), .B0 (n_75), .Y (out[10]));
  CLKAND2X2 g3058__2398(.A (n_36), .B (n_63), .Y (n_97));
  AOI2BB1X2 g3045__5107(.A0N (n_32), .A1N (state[2]), .B0 (n_93), .Y
       (n_88));
  AND2X1 g3057__6260(.A (n_51), .B (n_81), .Y (n_100));
  OAI2BB1X1 g3022__4319(.A0N (count[1]), .A1N (n_79), .B0 (n_67), .Y
       (out[1]));
  OAI21X1 g3030__8428(.A0 (n_77), .A1 (n_76), .B0 (n_75), .Y (out[8]));
  OAI21X1 g3025__5526(.A0 (count[4]), .A1 (n_73), .B0 (n_71), .Y
       (out[6]));
  NAND2X1 g3028__6783(.A (n_61), .B (n_71), .Y (out[5]));
  OAI21X1 g3029__3680(.A0 (n_77), .A1 (n_69), .B0 (n_71), .Y (out[4]));
  OAI21X1 g3026__1617(.A0 (count[4]), .A1 (n_84), .B0 (n_67), .Y
       (out[2]));
  NAND2X1 g3023__2802(.A (n_57), .B (n_75), .Y (out[9]));
  INVX1 g3040(.A (n_75), .Y (out[11]));
  INVX1 g3038(.A (n_67), .Y (out[3]));
  INVX3 g3083(.A (n_63), .Y (n_119));
  OAI32X1 g3050__5122(.A0 (n_101), .A1 (n_22), .A2 (flick), .B0 (n_61),
       .B1 (n_26), .Y (n_62));
  INVX1 g3039(.A (n_71), .Y (out[7]));
  OAI21X2 g3054__8246(.A0 (n_58), .A1 (n_57), .B0 (n_55), .Y (out[13]));
  OAI21X2 g3044__7098(.A0 (n_77), .A1 (n_35), .B0 (n_55), .Y (out[12]));
  OAI21X2 g3052__6131(.A0 (count[4]), .A1 (n_53), .B0 (n_55), .Y
       (out[0]));
  NOR2X1 g3062__5115(.A (count[2]), .B (n_57), .Y (n_51));
  AOI211X1 g3060__7482(.A0 (count[3]), .A1 (state[1]), .B0 (state[2]),
       .C0 (n_37), .Y (n_50));
  NOR2X6 g3093__4733(.A (n_24), .B (reset), .Y (n_63));
  OAI21X4 g3070__6161(.A0 (n_79), .A1 (state[2]), .B0 (n_46), .Y
       (n_93));
  OR2X1 g3099__9315(.A (count[3]), .B (state[2]), .Y (n_48));
  NOR3BX1 g3051__9945(.AN (n_53), .B (count[4]), .C (n_46), .Y (n_47));
  NAND2BX1 g3043__2883(.AN (out[15]), .B (n_42), .Y (out[14]));
  NOR2X4 g3047__2346(.A (n_11), .B (out[15]), .Y (n_67));
  NOR2X4 g3048__1666(.A (n_21), .B (out[15]), .Y (n_71));
  NOR2X4 g3049__7410(.A (n_34), .B (out[15]), .Y (n_75));
  INVX3 g3065(.A (out[15]), .Y (n_55));
  AOI21X2 g3066__6417(.A0 (count[3]), .A1 (n_29), .B0 (n_20), .Y
       (n_41));
  AOI2BB1X1 g3053__5477(.A0N (state[0]), .A1N (n_53), .B0 (n_90), .Y
       (n_40));
  OAI22X2 g3055__2398(.A0 (n_38), .A1 (n_8), .B0 (n_58), .B1 (n_37), .Y
       (n_39));
  NAND2X1 g3061__5107(.A (state[0]), .B (n_73), .Y (n_36));
  INVX2 g3072(.A (n_34), .Y (n_35));
  NOR3BX1 g3067__6260(.AN (n_32), .B (n_5), .C (n_101), .Y (n_33));
  MX2X1 g3069__4319(.A (n_84), .B (n_18), .S0 (n_38), .Y (n_31));
  OR2X4 g3064__8428(.A (n_76), .B (n_73), .Y (n_42));
  NOR2X8 g3071__5526(.A (n_2), .B (n_10), .Y (out[15]));
  AOI2BB1X1 g3086__3680(.A0N (count[0]), .A1N (n_14), .B0 (n_27), .Y
       (n_28));
  NAND2X1 g3074__1617(.A (n_9), .B (n_25), .Y (n_26));
  INVX1 g3107(.A (n_23), .Y (n_24));
  OR2X1 g3077__2802(.A (count[1]), .B (n_22), .Y (n_105));
  NOR2X4 g3073__1705(.A (n_13), .B (flick), .Y (n_20));
  NOR2X1 g3088__5122(.A (n_84), .B (state[0]), .Y (n_19));
  NOR2X4 g3078__8246(.A (n_58), .B (n_76), .Y (n_34));
  NOR2X2 g3079__7098(.A (n_37), .B (flick), .Y (n_81));
  INVX1 g3108(.A (n_16), .Y (n_17));
  NAND2X2 g3111__1881(.A (state[1]), .B (state[2]), .Y (n_23));
  OR2X4 g3090__5115(.A (n_14), .B (n_69), .Y (n_61));
  CLKAND2X2 g3091__7482(.A (n_101), .B (n_13), .Y (n_46));
  NOR2X2 g3084__4733(.A (count[4]), .B (n_32), .Y (n_11));
  NAND2X6 g3075__6161(.A (count[4]), .B (n_9), .Y (n_10));
  NOR2X2 g3076__9315(.A (count[4]), .B (n_77), .Y (n_8));
  INVX1 g3095(.A (n_37), .Y (n_27));
  NAND2X6 g3081__9945(.A (count[2]), .B (n_3), .Y (n_73));
  INVX1 g3094(.A (n_13), .Y (n_25));
  NAND2X1 g3112__2883(.A (count[3]), .B (n_1), .Y (n_16));
  INVX1 g3109(.A (n_6), .Y (n_22));
  CLKAND2X2 g3092__2346(.A (n_32), .B (n_77), .Y (n_53));
  OR3X1 g3085__1666(.A (n_4), .B (count[1]), .C (count[4]), .Y (n_5));
  INVX1 g3098(.A (n_77), .Y (n_18));
  NOR2X1 g3113__7410(.A (n_4), .B (n_38), .Y (n_6));
  OR2X4 g3117__5477(.A (state[2]), .B (n_29), .Y (n_101));
  INVX2 g3097(.A (n_3), .Y (n_84));
  OR2X4 g3101__2398(.A (count[4]), .B (n_58), .Y (n_69));
  NAND2X2 g3103__6260(.A (n_4), .B (state[0]), .Y (n_37));
  NAND2X8 g3104__4319(.A (count[3]), .B (n_79), .Y (n_76));
  NOR2X6 g3100__8428(.A (count[0]), .B (count[3]), .Y (n_9));
  NOR2X2 g3116__5526(.A (state[0]), .B (reset), .Y (n_111));
  NOR2X8 g3106__6783(.A (count[0]), .B (count[1]), .Y (n_77));
  CLKAND2X3 g3105__3680(.A (count[0]), .B (count[1]), .Y (n_3));
  NOR2X6 g3115__1617(.A (count[3]), .B (count[2]), .Y (n_32));
  CLKINVX4 g3129(.A (count[1]), .Y (n_14));
  INVX2 g3127(.A (count[0]), .Y (n_4));
  CLKINVX8 g3124(.A (count[4]), .Y (n_79));
  INVX1 g3125(.A (reset), .Y (n_120));
  INVX3 g3130(.A (state[0]), .Y (n_38));
  CLKINVX8 g3128(.A (count[2]), .Y (n_58));
  NAND2X6 g3140__2802(.A (count[1]), .B (n_21), .Y (n_57));
  NAND2X6 g3142__1705(.A (n_58), .B (n_14), .Y (n_2));
  DFFRX4 \state_reg[2] (.RN (n_120), .CK (clk), .D (n_114), .Q
       (state[2]), .QN (n_1));
  DFFRX2 \state_reg[1] (.RN (n_120), .CK (clk), .D (n_106), .Q
       (state[1]), .QN (n_29));
  NOR3BX2 g3147(.AN (n_53), .B (count[4]), .C (state[2]), .Y (n_129));
  NOR2X1 g3089__3149(.A (count[2]), .B (n_18), .Y (n_92));
  NOR2X1 g3114__3151(.A (count[3]), .B (n_38), .Y (n_90));
  OAI2BB1X1 g3087__3153(.A0N (n_58), .A1N (n_29), .B0 (n_16), .Y
       (n_30));
  NAND2BX1 g3155(.AN (n_42), .B (state[0]), .Y (n_128));
  NAND2X2 g3102__3157(.A (state[2]), .B (n_29), .Y (n_13));
  INVX3 g3159(.A (n_76), .Y (n_21));
endmodule

